"use client";

import { useEffect, useRef, useState, type FormEvent } from "react";
import { Icon, SourceIcon } from "@/components/jeff/icons";
import { useJeff } from "@/components/jeff/store";
import { AddNoteModal, ChatScopeModal, DocModal } from "@/components/jeff/shared";
import { sourceDef } from "@/lib/jeff/sources";

async function copyText(text: string) {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

export function AgentPanel() {
  const jeff = useJeff();
  const [input, setInput] = useState("");
  const scrollRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const ids = jeff.connectedSources();

  useEffect(() => {
    const el = scrollRef.current;
    if (el) el.scrollTop = el.scrollHeight;
  }, [jeff.messages, jeff.busy]);

  useEffect(() => {
    if (jeff.agentOpen) setTimeout(() => inputRef.current?.focus(), 40);
  }, [jeff.agentOpen]);

  function submit(e?: FormEvent) {
    e?.preventDefault();
    const q = input;
    setInput("");
    void jeff.ask(q);
  }

  const disclaimer = jeff.aiEnabled
    ? `Answers are generated by Claude using narrow server-side tools. Daily cap $${jeff.aiBudgetUsd.toFixed(2)}. Check the cited sources.`
    : jeff.mode === "demo"
      ? "Demo answers use sample memories, not a live AI model."
      : "Extractive preview of synced context. Add ANTHROPIC_API_KEY to enable Jeff's AI.";

  return (
    <aside className={`agent-panel ${jeff.agentOpen ? "open" : ""}`} id="agentPanel" aria-label="Jeff assistant">
      <header className="agent-header">
        <span className="agent-mark">
          <Icon name="sparkles" />
        </span>
        <div>
          <h2>Ask Jeff</h2>
          <span>{jeff.aiEnabled ? "AI enabled / grounded in your sources" : "Your analyst. Your coordinator."}</span>
        </div>
        <button className="icon-button" id="newChat" type="button" aria-label="Start a new conversation" onClick={jeff.newChat}>
          <Icon name="compose" />
        </button>
        <button className="icon-button close-agent" type="button" aria-label="Close assistant" onClick={() => jeff.setAgentOpen(false)}>
          <Icon name="x" />
        </button>
      </header>
      <div className="chat-scroll" ref={scrollRef}>
        {jeff.messages.length === 0 ? (
          <div className="chat-welcome">
            <div className="agent-orbit">
              <span className="orbit orbit-one" />
              <span className="orbit orbit-two" />
              <span className="orbit orbit-three" />
              <span className="orbit-center">
                <Icon name="sparkles" />
              </span>
              <span className="orbit-dot od1" />
              <span className="orbit-dot od2" />
              <span className="orbit-dot od3" />
            </div>
            <div className="eyebrow">YOUR PERSONAL THINKING PARTNER</div>
            <h3>Hola, I&apos;m Jeff.</h3>
            <p>
              Find the signal. Give it direction.
              <br />
              Keep the important decisions yours.
            </p>
            <div className="suggestions-label">START WITH THE NEXT RIGHT THING</div>
            <Suggestion icon="sun" title="What needs my attention?" sub="Find what matters across your sources" prompt="What needs my attention this week?" />
            <Suggestion icon="layers" title="How would we fix duplicate leads?" sub="Investigate, prepare, test, then approve" prompt="How would we fix duplicate leads?" />
            <Suggestion icon="calendar" title="Help me prepare for my week" sub="Meetings, context, and next steps" prompt="What meetings are coming up?" />
            <Suggestion icon="plug" title="Which connections are live?" sub="Status of every integration" prompt="Which of my connections are working right now?" />
            <div className="agent-note">
              <Icon name="link" />
              Answers that take you back to the source.
            </div>
          </div>
        ) : null}
        <div aria-live="polite">
          {jeff.messages.map((m, i) => (
            <article className={`chat-message ${m.role}`} key={i}>
              <div className="message-heading">
                <Icon name={m.role === "user" ? "user" : "sparkles"} />
                <span>{m.role === "user" ? "YOU" : m.ai ? "JEFF / AI" : "JEFF / EXTRACTIVE PREVIEW"}</span>
              </div>
              <div className="message-text" style={{ whiteSpace: "pre-wrap" }}>
                {m.text}
              </div>
              {m.refs?.length ? (
                <div className="citation-chips">
                  {m.refs.map((r, j) => (
                    <button key={r.id} type="button" className="citation-chip" onClick={() => jeff.openModal(<DocModal doc={r} />)}>
                      <span className="citation-num">{j + 1}</span>
                      <SourceIcon id={r.source} />
                      <span>{r.title}</span>
                      <Icon name="arrowUpRight" />
                    </button>
                  ))}
                </div>
              ) : null}
              {m.citations?.length ? (
                <div className="citation-chips">
                  {m.citations.map((c, j) =>
                    c.url ? (
                      <a key={j} className="citation-chip" href={c.url} target="_blank" rel="noopener noreferrer">
                        <span className="citation-num">{j + 1}</span>
                        <span>{c.title}</span>
                        <Icon name="arrowUpRight" />
                      </a>
                    ) : (
                      <span key={j} className="citation-chip">
                        <span className="citation-num">{j + 1}</span>
                        <span>{c.title}</span>
                      </span>
                    ),
                  )}
                </div>
              ) : null}
              {m.role === "assistant" ? (
                <div className="message-actions">
                  <button type="button" onClick={() => jeff.saveAnswer(m)}>
                    <Icon name="bookmark" />
                    Save answer
                  </button>
                  <button
                    type="button"
                    onClick={async () => {
                      jeff.toast((await copyText(m.text)) ? "Copied to clipboard." : "Clipboard unavailable.");
                    }}
                  >
                    <Icon name="copy" />
                    Copy
                  </button>
                  {m.toolsUsed?.length ? <span style={{ fontSize: 10, color: "var(--muted)" }}>tools: {m.toolsUsed.join(", ")}</span> : null}
                </div>
              ) : null}
            </article>
          ))}
          {jeff.busy ? (
            <div className="typing">
              <span />
              <span />
              <span />
              &nbsp; {jeff.aiEnabled ? "Connecting your context..." : "Finding relevant memories..."}
            </div>
          ) : null}
        </div>
      </div>
      <div className="composer-area">
        <div className="context-bar">
          <div className="context-source-icons">
            {ids.slice(0, 6).map((id) => (
              <SourceIcon key={id} id={id} />
            ))}
          </div>
          <button className="context-scope" type="button" onClick={() => jeff.openModal(<ChatScopeModal />)}>
            {jeff.chatScope === "all" ? "All sources" : sourceDef(jeff.chatScope).name}
            <Icon name="chevronDown" />
          </button>
          <span className="context-status">{jeff.aiEnabled ? "AI enabled" : "Preview"}</span>
        </div>
        <form className="composer" onSubmit={submit}>
          <textarea
            ref={inputRef}
            rows={2}
            placeholder="Ask Jeff anything..."
            aria-label="Ask Jeff a question"
            maxLength={4000}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter" && !e.shiftKey) {
                e.preventDefault();
                submit();
              }
            }}
          />
          <div className="composer-tools">
            <button type="button" className="icon-button" aria-label="Add a note as context" onClick={() => jeff.openModal(<AddNoteModal />)}>
              <Icon name="plus" />
            </button>
            <span>
              <Icon name="sparkles" />
              {jeff.aiEnabled ? "AI + your connected context" : "Context-aware preview"}
            </span>
            <button className="send-button" type="submit" aria-label="Send message" disabled={jeff.busy}>
              <Icon name="arrowUp" />
            </button>
          </div>
        </form>
        <p className="chat-disclaimer">{disclaimer}</p>
      </div>
    </aside>
  );
}

function Suggestion({ icon, title, sub, prompt }: { icon: string; title: string; sub: string; prompt: string }) {
  const { ask } = useJeff();
  return (
    <button className="suggestion" type="button" onClick={() => ask(prompt)}>
      <Icon name={icon} />
      <span>
        {title}
        <small>{sub}</small>
      </span>
      <Icon name="arrowUpRight" />
    </button>
  );
}
