/**
 * Grouping engine (pure): live alerts + live obligations in, group plans out.
 *
 * Principle: surface the underlying problem, not every individual signal
 * generated by that problem. Structured relationships (client id, goal id,
 * mission id, workflow, ad account) decide membership; name/keyword matching
 * is only used to attach free-text follow-through items to a client that is
 * already known. Individual records are never merged — a plan only says which
 * existing records belong together.
 */
import { clientByName, entityKeyForAlert, groupKeyOf, issueOfCategory, issueOfText, type ClientLite, type EntityKey, type EntityKind, type IssueKind } from "./keys";
import { buildSummary, type MemberDetail, type SummaryFacts } from "./summary";

export type GroupImportance = "informational" | "briefing" | "important" | "urgent" | "actionable";
const RANK: Record<GroupImportance, number> = { informational: 0, briefing: 1, important: 2, actionable: 2.5, urgent: 3 };

export interface GroupableAlert {
  id: string;
  fingerprint: string;
  kind: string;
  ref_id: string | null;
  category: string | null;
  importance: GroupImportance;
  scope: "business" | "personal" | "financial" | "all";
  status: string;
  title: string;
  summary: string | null;
  first_seen: string;
  last_seen: string;
  group_id: string | null;
}

export interface GroupableFinding {
  id: string;
  category: string;
  title: string;
  goal_id: string | null;
  severity: string;
  metrics: Record<string, unknown>;
  observed_facts: string[];
  /** Per-task rows when the finding lists portal tasks (filled by the store from evidence). */
  items?: MemberDetail["items"];
}

export interface GroupableObligation {
  id: string;
  title: string;
  description: string | null;
  status: string;
  scope: string;
  priority: string;
  due_at: string | null;
  assigned_to: "me" | "other";
  waiting_on: string | null;
  counterparty: string | null;
  related_client_id: string | null;
  related_goal_id: string | null;
  related_mission_id: string | null;
  source_provider: string | null;
  origin: string;
  metadata: Record<string, unknown>;
}

export interface GroupableCommitment {
  id: string;
  counterparty: string | null;
  action_text: string;
}

export interface GroupingInput {
  now: Date;
  alerts: GroupableAlert[];
  findings: GroupableFinding[];
  obligations: GroupableObligation[];
  commitments: GroupableCommitment[];
  clients: ClientLite[];
  goalNames?: Map<string, string>;
}

export interface PlannedMember {
  member_kind: "alert" | "obligation";
  member_id: string;
  alert_id: string | null;
  title: string;
  key_source: "structured" | "semantic";
  importance: GroupImportance;
  detail: MemberDetail;
}

export interface GroupPlan {
  group_key: string;
  entity_kind: EntityKind;
  entity_id: string;
  entity_name: string;
  issue_kind: IssueKind;
  title: string;
  summary: string;
  facts: SummaryFacts;
  importance: GroupImportance;
  scope: "business" | "personal" | "financial" | "all";
  members: PlannedMember[];
  /** Stable hash of the member set (ids sorted) — drives count-change detection and re-interpretation. */
  member_hash: string;
}

export const MIN_GROUP_SIZE = 2;

/** Alert statuses that make an alert a live signal (grouped = already under a group, still live). */
const LIVE_ALERT = new Set(["open", "acknowledged", "snoozed", "grouped"]);
const LIVE_OBLIGATION = new Set(["open", "due", "overdue", "waiting_on_me", "waiting_on_other", "possibly_complete", "snoozed"]);

interface Bucket {
  entity: EntityKey;
  issue: IssueKind;
  members: PlannedMember[];
  scopes: Set<string>;
  /** True when at least one member's family came from a category (not a keyword guess). */
  categorized: boolean;
}

function daysOverdue(due: string | null, now: Date): number | null {
  if (!due) return null;
  const d = Math.floor((now.getTime() - Date.parse(due)) / 86_400_000);
  return d >= 0 ? d : null;
}

function obligationDetail(o: GroupableObligation, now: Date): MemberDetail {
  return {
    kind: "obligation",
    category: null,
    due_at: o.due_at,
    days_overdue: daysOverdue(o.due_at, now),
    owner: o.assigned_to === "other" ? (o.waiting_on ?? o.counterparty ?? "Someone else") : "You",
    priority: o.priority,
    status: o.status,
    notes: o.description ? o.description.slice(0, 240) : null,
    blocking: false,
    source: o.source_provider ?? o.origin,
    href: "/follow-through",
  };
}

function findingDetail(a: GroupableAlert, f: GroupableFinding | undefined): MemberDetail {
  const m = f?.metrics ?? {};
  const oldest = typeof m.oldest_overdue_days === "number" ? Math.round(m.oldest_overdue_days) : typeof m.oldest_days === "number" ? Math.round(m.oldest_days) : null;
  const blocking = typeof m.blocking === "number" ? m.blocking > 0 : false;
  return {
    kind: "finding",
    category: a.category,
    due_at: null,
    days_overdue: oldest,
    owner: typeof m.owed_by_bizgrips === "number" && m.owed_by_bizgrips > 0 ? "BizGrips" : typeof m.owed_by_client === "number" && m.owed_by_client > 0 ? "Client" : null,
    priority: f?.severity ?? null,
    status: a.status === "grouped" ? "open" : a.status,
    notes: (f?.observed_facts ?? []).slice(0, 3).join(" ").slice(0, 400) || a.summary?.slice(0, 240) || null,
    blocking,
    source: "finding",
    href: "/insights",
    items: f?.items ?? [],
    count: typeof m.overdue_total === "number" ? m.overdue_total : typeof m.invoices === "number" ? m.invoices : typeof m.leads_new_over_threshold === "number" ? m.leads_new_over_threshold : undefined,
  };
}

function hashOf(ids: string[]): string {
  // Small deterministic string hash (FNV-1a) over the sorted member ids; no crypto needed.
  let h = 0x811c9dc5;
  for (const ch of [...ids].sort().join("|")) {
    h ^= ch.charCodeAt(0);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h.toString(16).padStart(8, "0");
}

export function planGroups(input: GroupingInput): GroupPlan[] {
  const { now, clients } = input;
  const goalNames = input.goalNames ?? new Map<string, string>();
  const findingById = new Map(input.findings.map((f) => [f.id, f]));
  const obligationById = new Map(input.obligations.map((o) => [o.id, o]));
  const commitmentById = new Map(input.commitments.map((c) => [c.id, c]));
  const buckets = new Map<string, Bucket>();
  const seenObligations = new Set<string>();

  const add = (entity: EntityKey, issue: IssueKind, member: PlannedMember, scope: string, categorized: boolean) => {
    const key = groupKeyOf(entity, issue);
    const b = buckets.get(key) ?? { entity, issue, members: [], scopes: new Set<string>(), categorized: false };
    if (b.members.some((m) => m.member_kind === member.member_kind && m.member_id === member.member_id)) return;
    b.members.push(member);
    b.scopes.add(scope);
    b.categorized = b.categorized || categorized;
    buckets.set(key, b);
  };

  // Free-text items (obligations / commitments) are held back until categorized families exist per client,
  // so the keyword tie-breaker can attach them to the client's dominant situation.
  const deferred: { entity: EntityKey; issue: IssueKind; member: PlannedMember; scope: string }[] = [];

  for (const a of input.alerts) {
    if (!LIVE_ALERT.has(a.status)) continue;
    if (a.kind === "group" || a.kind === "system") continue;
    if (a.category === "blind_spot") continue; // blind spots have their own daily batch
    const finding = a.kind === "finding" && a.ref_id ? findingById.get(a.ref_id) : undefined;
    const obligation = a.kind === "obligation" && a.ref_id ? obligationById.get(a.ref_id) : undefined;
    const commitment = a.kind === "commitment" && a.ref_id ? commitmentById.get(a.ref_id) : undefined;
    const entity = entityKeyForAlert(
      {
        kind: a.kind,
        fingerprint: a.fingerprint,
        category: a.category,
        title: a.title,
        ref_id: a.ref_id,
        goal_id: finding?.goal_id ?? null,
        related_client_id: obligation?.related_client_id ?? null,
        related_goal_id: obligation?.related_goal_id ?? null,
        related_mission_id: obligation?.related_mission_id ?? null,
        counterparty: obligation?.counterparty ?? obligation?.waiting_on ?? null,
        commitment_counterparty: commitment?.counterparty ?? null,
      },
      clients,
      goalNames,
    );
    if (!entity) continue;
    if (a.kind === "obligation" && obligation) {
      seenObligations.add(obligation.id);
      const member: PlannedMember = { member_kind: "obligation", member_id: obligation.id, alert_id: a.id, title: obligation.title, key_source: entity.source, importance: a.importance, detail: obligationDetail(obligation, now) };
      deferred.push({ entity, issue: issueOfText(`${obligation.title} ${obligation.description ?? ""}`), member, scope: a.scope });
      continue;
    }
    if (a.kind === "commitment") {
      const member: PlannedMember = { member_kind: "alert", member_id: a.id, alert_id: a.id, title: a.title, key_source: entity.source, importance: a.importance, detail: { kind: "commitment", category: a.category, due_at: null, days_overdue: null, owner: null, priority: null, status: a.status === "grouped" ? "open" : a.status, notes: a.summary?.slice(0, 240) ?? null, blocking: false, source: "commitment", href: "/follow-through" } };
      deferred.push({ entity, issue: issueOfText(a.title), member, scope: a.scope });
      continue;
    }
    const issue = a.kind === "goal" ? "goal" : issueOfCategory(a.category);
    const member: PlannedMember = { member_kind: "alert", member_id: a.id, alert_id: a.id, title: a.title, key_source: entity.source, importance: a.importance, detail: a.kind === "goal" ? { kind: "goal", category: a.category, due_at: null, days_overdue: null, owner: null, priority: null, status: a.status === "grouped" ? "open" : a.status, notes: a.summary?.slice(0, 240) ?? null, blocking: false, source: "goal", href: `/goals#${a.ref_id ?? ""}` } : findingDetail(a, finding) };
    add(entity, issue, member, a.scope, issue !== "mixed");
  }

  // Live obligations with no reminder alert yet still belong to the situation (they are what is owed).
  for (const o of input.obligations) {
    if (seenObligations.has(o.id) || !LIVE_OBLIGATION.has(o.status)) continue;
    if (o.scope === "personal") continue; // personal errands never join business situations
    let entity: EntityKey | null = null;
    if (o.related_client_id) entity = { kind: "client", id: o.related_client_id, name: clients.find((c) => c.portal_client_id === o.related_client_id)?.name ?? `Client ${o.related_client_id}`, source: "structured" };
    else if (o.related_goal_id) entity = { kind: "goal", id: o.related_goal_id, name: goalNames.get(o.related_goal_id) ?? "Goal", source: "structured" };
    else if (o.related_mission_id) entity = { kind: "mission", id: o.related_mission_id, name: "Mission", source: "structured" };
    else {
      const byName = clientByName(o.title, clients) ?? clientByName(o.counterparty, clients) ?? clientByName(o.waiting_on, clients);
      if (byName) entity = { kind: "client", id: byName.portal_client_id, name: byName.name, source: "semantic" };
    }
    if (!entity) continue;
    const member: PlannedMember = { member_kind: "obligation", member_id: o.id, alert_id: null, title: o.title, key_source: entity.source, importance: "briefing", detail: obligationDetail(o, now) };
    deferred.push({ entity, issue: issueOfText(`${o.title} ${o.description ?? ""}`), member, scope: o.scope === "all" ? "business" : o.scope });
  }

  // Tie-breaker: a free-text item joins the entity's largest categorized family when its own keyword family
  // has no categorized signals; otherwise it keeps its keyword family.
  for (const d of deferred) {
    let issue = d.issue;
    if (d.entity.kind === "client") {
      const own = buckets.get(groupKeyOf(d.entity, issue));
      if (!own?.categorized) {
        const families = [...buckets.values()].filter((b) => b.entity.kind === "client" && b.entity.id === d.entity.id && b.categorized).sort((a, b) => b.members.length - a.members.length);
        if (families[0]) issue = families[0].issue;
      }
    } else issue = d.entity.kind === "goal" ? "goal" : "follow_through";
    add(d.entity, issue, { ...d.member, key_source: d.member.key_source === "semantic" || issue !== d.issue ? "semantic" : "structured" }, d.scope, false);
  }

  const plans: GroupPlan[] = [];
  for (const [group_key, b] of buckets) {
    if (b.members.length < MIN_GROUP_SIZE) continue;
    const importance = b.members.reduce<GroupImportance>((acc, m) => (RANK[m.importance] > RANK[acc] ? m.importance : acc), "informational");
    const scope: GroupPlan["scope"] = b.scopes.has("financial") && b.scopes.size === 1 ? "financial" : b.scopes.has("personal") && b.scopes.size === 1 ? "personal" : "business";
    const { title, summary, facts } = buildSummary({ entity: b.entity, issue: b.issue, members: b.members, now });
    plans.push({ group_key, entity_kind: b.entity.kind, entity_id: b.entity.id, entity_name: b.entity.name, issue_kind: b.issue, title, summary, facts, importance, scope, members: b.members, member_hash: hashOf(b.members.map((m) => `${m.member_kind}:${m.member_id}`)) });
  }
  return plans.sort((a, b) => RANK[b.importance] - RANK[a.importance] || b.members.length - a.members.length || a.title.localeCompare(b.title));
}
