import type { JobInput, NotificationPolicy } from "./types";

/**
 * System job definitions — the roster of analysts Gomez runs for the owner.
 * Declarative only. `detectors` reference the detector registry; an empty
 * list with `pending` means the analyst is defined but its detectors arrive
 * in a later run (shown as DRAFT · coming next in the UI). Jobs whose sources
 * are not connected still run with LIMITED COVERAGE.
 */

export type TemplateCategory = "Sales" | "Finance" | "Operations" | "Clients" | "Relationships" | "Personal" | "Goals" | "Productivity" | "Automation" | "Follow-Through";

export interface SystemJobDefinition extends JobInput {
  template_category: TemplateCategory;
  /** Human list of what it looks for (shown in the detail view). */
  looks_for: string[];
  /** Detectors arrive in a later run; job is seeded as draft. */
  pending?: string;
  /** Prominent UI alias (e.g. "Find what I'm missing"). */
  ui_name?: string;
}

const P = (over: Partial<NotificationPolicy> = {}): NotificationPolicy => ({ min_importance: "important", push: true, briefing_only: false, max_per_day: 5, ...over });

export const SYSTEM_JOBS: SystemJobDefinition[] = [
  {
    slug: "revenue-leakage-hunter",
    name: "Revenue Leakage Hunter",
    icon: "search",
    description: "Finds money slipping through the cracks: unfollowed leads, stale proposals, failed payments, stuck opportunities.",
    purpose: "Every day, look for revenue that is leaking because something stopped moving — a lead nobody answered, a proposal nobody chased, a payment that failed, an opportunity aging in a stage.",
    scope: "business",
    job_type: "system",
    status: "active",
    schedule_type: "event_driven",
    schedule_expression: "07:05",
    timezone: null,
    notification_policy: P(),
    minimum_severity: "low",
    sources: ["highlevel", "stripe", "google", "meta", "portal"],
    detectors: ["lead_followup_gap", "pipeline_aging", "failed_payment", "client_unpaid_invoice", "underperforming_acquisition", "lead_not_contacted"],
    config: {},
    template_category: "Sales",
    looks_for: ["Unfollowed and uncontacted leads", "Stale proposals and aging opportunities", "Failed or overdue payments", "Qualified leads that went cold", "Acquisition that costs more than it returns"],
  },
  {
    slug: "relationship-radar",
    name: "Relationship Radar",
    icon: "user",
    description: "Watches important relationships for changes, upcoming events, promises, and meaningful periods of silence.",
    purpose: "Notice when a relationship that matters — a referral source, a client contact, a friend — goes quiet, resurfaces, or is owed a promise.",
    scope: "all",
    job_type: "system",
    status: "active",
    schedule_type: "daily",
    schedule_expression: "07:05",
    timezone: null,
    notification_policy: P({ min_importance: "important", max_per_day: 3 }),
    minimum_severity: "low",
    sources: ["google", "highlevel", "slack", "portal"],
    detectors: ["relationship_quiet", "referral_source_declining", "contact_resurfaced", "important_date"],
    config: { include_personal: true },
    template_category: "Relationships",
    looks_for: ["Important relationships going quiet", "Referral sources changing", "Promises outstanding (handed to Follow-Through)", "Contacts unexpectedly resurfacing", "Important dates you recorded"],
  },
  {
    slug: "client-health-analyst",
    name: "Client Health Analyst",
    icon: "shield",
    description: "Tracks each client's engagement, delivery progress, payments and silence so problems surface before they become churn.",
    purpose: "For every active client: is delivery moving, are they paying, are they engaged, and is anything quietly going wrong?",
    scope: "business",
    job_type: "system",
    status: "active",
    schedule_type: "daily",
    schedule_expression: "07:05",
    timezone: null,
    notification_policy: P(),
    minimum_severity: "low",
    sources: ["portal", "stripe", "highlevel", "meta", "google"],
    detectors: ["portal_task_overdue", "portal_stage_stalled", "client_unpaid_invoice", "client_ad_spend_no_leads", "portal_notification_failure", "quiet_client", "client_engagement_drop", "client_missed_meeting", "client_negative_signal"],
    config: {},
    template_category: "Clients",
    looks_for: ["Declining communication", "Payment issues", "Stalled onboarding", "Missed meetings and notification failures", "Ad spend without leads"],
  },
  {
    slug: "cash-flow-watchdog",
    name: "Cash Flow Watchdog",
    icon: "layers",
    description: "Watches failed payments, collections, unusual cash movement and cash-flow squeezes. Never moves money.",
    purpose: "Catch cash-flow problems early: failed payments, overdue invoices, big swings in inflow or outflow, large upcoming expenses.",
    scope: "financial",
    job_type: "system",
    status: "active",
    schedule_type: "event_driven",
    schedule_expression: "07:05",
    timezone: null,
    notification_policy: P(),
    minimum_severity: "low",
    sources: ["stripe", "plaid"],
    detectors: ["cashflow_change", "failed_payment", "client_unpaid_invoice"],
    config: {},
    template_category: "Finance",
    looks_for: ["Failed payments", "Collections changes", "Unusual cash movement", "Cash-flow squeezes", "Major recurring payment changes"],
  },
  {
    slug: "expense-creep-hunter",
    name: "Expense Creep Hunter",
    icon: "trash",
    description: "Finds new recurring charges, price increases, duplicate tools and renewals you may not want.",
    purpose: "Keep recurring spend honest: what's new, what went up, what looks duplicated or unused.",
    scope: "financial",
    job_type: "system",
    status: "active",
    schedule_type: "weekly",
    schedule_expression: "mon 07:05",
    timezone: null,
    notification_policy: P({ briefing_only: true }),
    minimum_severity: "low",
    sources: ["plaid", "stripe"],
    detectors: ["recurring_expense_change", "new_recurring_charge", "duplicate_tool", "price_increase", "unused_software", "annual_renewal_upcoming"],
    config: {},
    template_category: "Finance",
    looks_for: ["New recurring charges", "Price increases", "Duplicate or overlapping tools", "Annual renewals"],
  },
  {
    slug: "commitment-watchdog",
    name: "Commitment Watchdog",
    icon: "check",
    description: "Finds real promises — yours and others' — in email, CRM and Slack, and ignores system noise.",
    purpose: "Know what you promised, what was promised to you, and what is blocked on someone else. Heavily governed by your Memory & Rules.",
    scope: "all",
    job_type: "system",
    status: "active",
    schedule_type: "daily",
    schedule_expression: "07:05",
    timezone: null,
    notification_policy: P(),
    minimum_severity: "low",
    sources: ["google", "highlevel", "slack"],
    detectors: ["missed_commitment"],
    config: {},
    template_category: "Follow-Through",
    looks_for: ["Promises made by you", "Promises made to you", "Due dates", "Things waiting on others", "Things others are waiting on you for"],
  },
  {
    slug: "follow-through-watchdog",
    name: "Follow-Through Watchdog",
    icon: "refresh",
    description: "Makes sure reminders, tasks and obligations don't disappear because a notification was shown once.",
    purpose: "Track resolution, not delivery: an obligation stays alive until it is actually completed, dismissed, cancelled or intentionally abandoned.",
    scope: "all",
    job_type: "system",
    status: "active",
    // Hourly safety tick; syncs for its sources also trigger it (event-driven) via the runner's event hook.
    schedule_type: "hourly",
    schedule_expression: null,
    timezone: null,
    notification_policy: P({ max_per_day: 6, min_importance: "important" }),
    minimum_severity: "low",
    sources: ["google", "notion", "highlevel", "slack", "stripe", "plaid", "github", "n8n", "portal"],
    detectors: ["follow_through"],
    config: { event_triggers: true },
    template_category: "Follow-Through",
    looks_for: ["Open obligations", "Overdue items", "Waiting on you", "Waiting on someone else", "Possible completions to confirm"],
  },
  {
    slug: "automation-auditor",
    name: "Automation Auditor",
    icon: "settings",
    description: "Watches workflows and integrations for failures, repeated errors and broken webhooks.",
    purpose: "Keep automations trustworthy: surface failed workflows, notification failures and stale integrations before they cost a lead or a client.",
    scope: "business",
    job_type: "system",
    status: "active",
    schedule_type: "event_driven",
    schedule_expression: "07:05",
    timezone: null,
    notification_policy: P(),
    minimum_severity: "low",
    sources: ["n8n", "github", "portal"],
    detectors: ["automation_failure", "portal_notification_failure", "webhook_broken", "repeated_error", "duplicate_lead_events", "manual_repetition"],
    config: {},
    template_category: "Automation",
    looks_for: ["Failed n8n workflows", "Repeated errors", "Broken webhooks", "Stale integrations", "Manual repeated processes"],
  },
  {
    slug: "time-allocation-auditor",
    name: "Time Allocation Auditor",
    icon: "calendar",
    description: "Compares where your calendar time actually goes against your active goals.",
    purpose: "Show whether your week matches your priorities — e.g. how much scheduled time touches sales when sales is the #1 goal.",
    scope: "all",
    job_type: "system",
    status: "active",
    schedule_type: "weekly",
    schedule_expression: "mon 07:05",
    timezone: null,
    notification_policy: P({ briefing_only: true }),
    minimum_severity: "low",
    sources: ["google"],
    detectors: ["time_allocation_mismatch"],
    config: {},
    template_category: "Productivity",
    looks_for: ["Time on goal-related work vs everything else", "Weeks that drift from stated priorities"],
  },
  {
    slug: "attention-cost-detector",
    name: "Attention Cost Detector",
    icon: "sun",
    description: "Finds fragmented days, meeting overload and missing focus blocks — from evidence, not generic advice.",
    purpose: "Quantify context switching and meeting load so you can protect focus time deliberately.",
    scope: "all",
    job_type: "system",
    status: "active",
    schedule_type: "weekly",
    schedule_expression: "mon 07:05",
    timezone: null,
    notification_policy: P({ briefing_only: true }),
    minimum_severity: "low",
    sources: ["google", "slack"],
    detectors: ["attention_fragmentation"],
    config: {},
    template_category: "Productivity",
    looks_for: ["Fragmented workdays", "Too many short meetings", "No focus blocks", "Reactive communication patterns"],
  },
  {
    slug: "personal-project-tracker",
    name: "Personal Project Tracker",
    icon: "bookmark",
    description: "Keeps personal projects, purchases, renewals and deadlines moving — only from data you intentionally connected.",
    purpose: "Home projects, travel, learning, maintenance and personal deadlines, tracked with the same follow-through as business work.",
    scope: "personal",
    job_type: "system",
    status: "active",
    schedule_type: "weekly",
    schedule_expression: "sun 17:00",
    timezone: null,
    notification_policy: P({ briefing_only: true }),
    minimum_severity: "low",
    sources: ["google", "notion", "plaid"],
    detectors: ["personal_project_stalled", "personal_renewal_due"],
    config: {},
    template_category: "Personal",
    looks_for: ["Personal deadlines (handed to Follow-Through)", "Renewals and maintenance", "Stalled personal projects"],
  },
  {
    slug: "goal-coach",
    name: "Goal Coach",
    icon: "target",
    description: "Re-evaluates every active goal: trajectory, primary constraint, leading indicators, and what to do next.",
    purpose: "Daily and after relevant events, tell you whether each goal is on pace, what is holding it back, and which lever to pull.",
    scope: "all",
    job_type: "system",
    status: "active",
    schedule_type: "event_driven",
    schedule_expression: "07:05",
    timezone: null,
    notification_policy: P(),
    minimum_severity: "low",
    sources: ["highlevel", "stripe", "meta", "google", "portal"],
    detectors: ["goal_trajectory", "goal_coach"],
    config: {},
    template_category: "Goals",
    looks_for: ["Trajectory changes", "Primary constraint", "Leading indicators", "Meaningful risk", "Opportunities", "One coaching note per goal per week"],
  },
  {
    slug: "blind-spot-scanner",
    name: "Blind Spot Scanner",
    ui_name: "Find what I'm missing",
    icon: "brain",
    description: "Searches broadly across everything connected for important, novel things that have not already been surfaced.",
    purpose: "Find important, novel observations Noah may be missing: contradictions, neglect, anomalies, opportunities, risks, stale decisions, behavior vs intention, unresolved obligations.",
    scope: "all",
    job_type: "system",
    status: "active",
    schedule_type: "weekly",
    schedule_expression: "mon 07:15",
    timezone: null,
    notification_policy: P({ max_per_day: 2 }),
    minimum_severity: "low",
    sources: ["google", "highlevel", "stripe", "slack", "portal", "plaid", "meta", "notion", "github", "n8n"],
    detectors: ["blind_spots"],
    config: {},
    template_category: "Goals",
    looks_for: ["Contradictions", "Neglect", "Anomalies", "Opportunities", "Risks", "Stale decisions", "Behavior vs intention", "Unresolved obligations"],
  },
];

export const SYSTEM_JOB_SLUGS = SYSTEM_JOBS.map((j) => j.slug);

export function getSystemJob(slug: string): SystemJobDefinition | undefined {
  return SYSTEM_JOBS.find((j) => j.slug === slug);
}

/** Fields the seeder may refresh on existing rows (never owner-owned state). */
export const SEED_REFRESH_FIELDS = ["name", "icon", "description", "purpose", "sources", "detectors"] as const;
