import type { ProviderDefinition } from "./types";

/**
 * Provider registry. Everything here is public, non-secret configuration.
 * Scopes live next to each provider adapter (lib/integrations/providers/*).
 */
export const PROVIDERS: ProviderDefinition[] = [
  {
    id: "google",
    name: "Google Workspace",
    description: "Gmail, Google Drive, and Google Calendar through one read-only Google authorization.",
    color: "#75adff",
    connectionType: "knowledge_source",
    authType: "oauth2",
    access: "read",
    capabilities: [
      { id: "gmail", name: "Gmail", description: "Emails, conversations, and the details between the lines.", access: "read" },
      { id: "drive", name: "Google Drive", description: "Documents, proposals, and all the work behind your work.", access: "read" },
      { id: "calendar", name: "Google Calendar", description: "Meetings, upcoming events, and the context to show up ready.", access: "read" },
    ],
    requiredEnv: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
    docsUrl: "https://developers.google.com/identity/protocols/oauth2/web-server",
    setupSummary:
      "Create an OAuth client (Web application) in Google Cloud, add Jeff's callback URL, and put the client id/secret in Vercel. Then authorize once with read-only scopes.",
    permissionBoundary: "gmail.readonly, drive.readonly, calendar.events.readonly. No sending, no file edits, no event changes.",
    accessCaption: "Read-only by default",
  },
  {
    id: "slack",
    name: "Slack",
    description: "Team conversations, shared decisions, and quick updates.",
    color: "#9bafff",
    connectionType: "knowledge_source",
    authType: "oauth2",
    access: "read",
    capabilities: [{ id: "search", name: "Workspace search", description: "Search public channel history you can already see.", access: "read" }],
    requiredEnv: ["SLACK_CLIENT_ID", "SLACK_CLIENT_SECRET"],
    docsUrl: "https://api.slack.com/authentication/oauth-v2",
    setupSummary: "Create a Slack app, add the redirect URL, request only user read/search scopes, and store the client id/secret in Vercel.",
    permissionBoundary: "User-token search and public-channel read scopes. No posting, no DMs, no private channels unless explicitly enabled later.",
    accessCaption: "Read-only by default",
  },
  {
    id: "notion",
    name: "Notion",
    description: "Your wiki, project plans, and a home for every idea.",
    color: "#c5dfff",
    connectionType: "knowledge_source",
    authType: "oauth2",
    access: "read",
    capabilities: [{ id: "pages", name: "Shared pages", description: "Only the pages and databases you explicitly share.", access: "read" }],
    requiredEnv: ["NOTION_CLIENT_ID", "NOTION_CLIENT_SECRET"],
    docsUrl: "https://developers.notion.com/docs/authorization",
    setupSummary: "Create a public Notion integration with read-only content capabilities, add the redirect URI, and store the OAuth client id/secret in Vercel.",
    permissionBoundary: "Read content only, limited to pages you share with the integration during authorization.",
    accessCaption: "Read-only by default",
  },
  {
    id: "highlevel",
    name: "LeadConnector / HighLevel",
    description: "Contacts, client conversations, pipelines, and relationship context.",
    color: "#6fdbff",
    connectionType: "knowledge_source",
    authType: "oauth2",
    access: "read",
    capabilities: [
      { id: "contacts", name: "Contacts", description: "Read contacts and tags.", access: "read" },
      { id: "conversations", name: "Conversations", description: "Read conversation history.", access: "read" },
      { id: "opportunities", name: "Opportunities", description: "Read pipelines and stages.", access: "read" },
      { id: "calendars", name: "Calendars", description: "Read appointments.", access: "read" },
    ],
    requiredEnv: ["HIGHLEVEL_CLIENT_ID", "HIGHLEVEL_CLIENT_SECRET"],
    docsUrl: "https://marketplace.gohighlevel.com/docs/",
    setupSummary: "Create a Marketplace app in HighLevel, add the redirect URL, select read-only scopes, and store the client id/secret in Vercel. Multiple sub-account locations can be selected later.",
    permissionBoundary: "Read-only contacts, conversations, opportunities, calendars, locations, users. No outbound messages, contact or appointment changes.",
    accessCaption: "Read-only by default",
  },
  {
    id: "stripe",
    name: "Stripe",
    description: "Payments, invoices, subscriptions, customers, disputes, and billing signals.",
    color: "#8aa4ff",
    connectionType: "financial",
    authType: "api_key",
    access: "read",
    capabilities: [{ id: "reporting", name: "Reporting", description: "Customers, charges, invoices, subscriptions, products, refunds, disputes, payouts.", access: "read" }],
    requiredEnv: [],
    docsUrl: "https://docs.stripe.com/keys#limit-access",
    setupSummary: "Create a restricted key with read-only permissions in the Stripe Dashboard and enter it once in Jeff's protected form. It is encrypted immediately and never displayed again.",
    permissionBoundary: "Restricted read-only reporting key. No charges, refunds, payouts, transfers, or subscription changes.",
    accessCaption: "Read-only reporting key",
  },
  {
    id: "plaid",
    name: "Financial Accounts",
    description: "Read-only bank and card balances, transactions, recurring expenses, and cash-flow signals. Powered by Plaid.",
    color: "#45c9ff",
    connectionType: "financial",
    authType: "plaid_link",
    access: "read",
    capabilities: [{ id: "transactions", name: "Transactions", description: "Transactions and account metadata only.", access: "read" }],
    requiredEnv: ["PLAID_CLIENT_ID", "PLAID_SECRET", "PLAID_ENV"],
    docsUrl: "https://plaid.com/docs/transactions/",
    setupSummary: "Add Plaid client id and secret to Vercel (sandbox first). Connect each institution through Plaid Link; access tokens are stored encrypted server-side.",
    permissionBoundary: "Plaid Transactions only. No Auth, Transfer, Payment Initiation, or money movement.",
    accessCaption: "Powered by Plaid · Read-only · No money movement",
  },
  {
    id: "meta",
    name: "Meta",
    description: "Meta Ads reporting, Facebook Pages, and Instagram Professional insights through one Meta app authorization.",
    color: "#5b9dff",
    connectionType: "knowledge_source",
    authType: "oauth2",
    access: "read",
    capabilities: [
      { id: "ads", name: "Meta Ads", description: "Campaign spend, delivery, and performance reporting.", access: "read" },
      { id: "pages", name: "Facebook Pages", description: "Page content, engagement, and insights.", access: "read" },
      { id: "instagram", name: "Instagram Professional", description: "Professional account content and insights.", access: "read" },
    ],
    requiredEnv: ["META_APP_ID", "META_APP_SECRET"],
    docsUrl: "https://developers.facebook.com/docs/facebook-login/guides/advanced/manual-flow",
    setupSummary: "Create a Meta app (Business type), add Facebook Login with the redirect URI, and store the app id/secret in Vercel. After authorizing, choose which ad accounts, Pages, and Instagram accounts Jeff may analyze.",
    permissionBoundary: "Read-only: ads_read, pages_read_engagement, pages_show_list, instagram_basic, instagram_manage_insights, business_management. No posting, messaging, budget changes, or campaign control.",
    accessCaption: "Read-only by default",
  },
  {
    id: "github",
    name: "GitHub",
    description: "Repositories, pull requests, tests, and technical context.",
    color: "#acd3ff",
    connectionType: "action_tool",
    authType: "github_app",
    access: "read_write",
    capabilities: [
      { id: "repos", name: "Selected repositories", description: "Read code, issues, and checks.", access: "read" },
      { id: "pull_requests", name: "Branches & pull requests", description: "Create branches, commit, open PRs. Merge stays approval-gated.", access: "read_write" },
    ],
    requiredEnv: ["GITHUB_APP_ID", "GITHUB_APP_CLIENT_ID", "GITHUB_APP_CLIENT_SECRET", "GITHUB_APP_PRIVATE_KEY_B64", "GITHUB_APP_WEBHOOK_SECRET"],
    docsUrl: "https://docs.github.com/en/apps/creating-github-apps",
    setupSummary: "Create a GitHub App with contents/pull requests/checks permissions, install it on selected repositories only, and store the app id, client id/secret, and base64 private key in Vercel.",
    permissionBoundary: "Selected repositories only. Contents + pull requests read/write, checks read. No admin, org, secrets, or branch-protection bypass.",
    accessCaption: "Read + prepare; approve production writes",
  },
  {
    id: "n8n",
    name: "n8n",
    description: "Workflow definitions, execution history, and approved routines.",
    color: "#67d4ef",
    connectionType: "action_tool",
    authType: "api_key",
    access: "read_write",
    capabilities: [
      { id: "workflows_read", name: "Workflow read", description: "List workflows and executions.", access: "read" },
      { id: "workflows_test", name: "Test workflows", description: "Create/update workflows tagged for testing.", access: "read_write" },
    ],
    requiredEnv: ["N8N_BASE_URL", "N8N_API_KEY"],
    docsUrl: "https://docs.n8n.io/api/",
    setupSummary: "Create an n8n API key in Settings → n8n API and store it in Vercel as N8N_API_KEY with N8N_BASE_URL. Jeff calls a server-side adapter; Claude never receives the key.",
    permissionBoundary: "Read workflows and executions; write only to test workflows. Production workflow changes require approval and are disabled in V1.",
    accessCaption: "Read + prepare; approve production writes",
  },
  {
    id: "claude",
    name: "Claude technical worker",
    description: "Your technical worker for investigation, code changes, workflow drafts, and tests. Jeff coordinates; you authorize consequential actions.",
    color: "#80bdff",
    connectionType: "worker",
    authType: "api_key",
    access: "read_write",
    capabilities: [
      { id: "ask", name: "Ask Jeff", description: "Server-side chat grounded in your connected context.", access: "read" },
      { id: "worker", name: "Sandbox worker", description: "Isolated Vercel Sandbox runs on approved missions.", access: "read_write" },
    ],
    requiredEnv: ["ANTHROPIC_API_KEY"],
    docsUrl: "https://docs.claude.com/en/api/overview",
    setupSummary: "Store ANTHROPIC_API_KEY in Vercel. Ask Jeff works immediately; sandbox execution stays approval-gated.",
    permissionBoundary: "Isolated task workspace, narrow brokered tools, budget and time limits, no raw credentials.",
    accessCaption: "Isolated worker · No raw credentials",
  },
];

export const PROVIDER_IDS = PROVIDERS.map((p) => p.id);

export function getProvider(id: string): ProviderDefinition | undefined {
  return PROVIDERS.find((p) => p.id === id);
}

export function isProviderId(id: string): boolean {
  return PROVIDERS.some((p) => p.id === id);
}

/** Legacy prototype source ids → registry provider + capability. */
export const LEGACY_SOURCE_MAP: Record<string, { provider: string; capability?: string }> = {
  gmail: { provider: "google", capability: "gmail" },
  drive: { provider: "google", capability: "drive" },
  calendar: { provider: "google", capability: "calendar" },
  slack: { provider: "slack" },
  notion: { provider: "notion" },
  leadconnector: { provider: "highlevel" },
  stripe: { provider: "stripe" },
  plaid: { provider: "plaid" },
  metaads: { provider: "meta", capability: "ads" },
  facebook: { provider: "meta", capability: "pages" },
  instagram: { provider: "meta", capability: "instagram" },
  github: { provider: "github" },
  n8n: { provider: "n8n" },
};
